### ISSUE TITLE
redstone_web_socket not being found?

### ISSUE THREAD

**Issue by Meai** [redstone-dart/redstone.dart#171]
pubspec.yml:

```
name: 'dart_server_test'
version: 0.0.1
description: A web server built using the shelf package.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  args: '>=0.10.0 <0.14.0'
  shelf: '>=0.6.0 <0.7.0'
  redstone: "^0.6.4"
  postgresql: "^0.3.3"
  redstone_web_socket: "0.1.0-beta.1"
```

pub get:

```
Resolving dependencies...
Package test has no versions that match >=0.12.1 <0.13.0 derived from:
- code_transformers 0.3.1 depends on version >=0.12.1 <0.13.0
```
